from data.scraping import query, process_response


def main(query_text: str):
    response = query(query_text)
    process_response(response, query_text)


if __name__ == "__main__":
    clothing_items = [
        "Capes & ponchos",
        "Duffle coats",
        "Faux fur coats",
        "Overcoats & long coats",
        "Parkas",
        "Peacoats",
        "Raincoats",
        "Trench coats",
        "Vests",
        "Biker & racer jackets",
        "Bomber jackets",
        "Denim jackets",
        "Field & utility jackets",
        "Fleece jackets",
        "Puffer jackets",
        "Quilted jackets",
        "Shackets",
        "Ski & snowboard jackets",
        "Varsity jackets",
        "Windbreakers",
        "Hoodies & sweatshirts",
        "V-neck sweaters",
        "Turtleneck sweaters",
        "Long sweaters",
        "Knitted sweaters",
        "3/4-sleeve sweaters",
        "Other sweaters",
        "Kimonos",
        "Cardigans",
        "Boleros",
        "Vests",
        "Other jumpers & sweaters",
        "Blazers",
        "Pantsuits",
        "Skirt suits",
        "Suit separates",
        "Other suits & blazers",
        "Mini-dresses",
        "Midi-dresses",
        "Long dresses",
        "Party & cocktail dresses",
        "Wedding dresses",
        "Prom dresses",
        "Evening dresses",
        "Backless dresses",
        "Summer dresses",
        "Winter dresses",
        "Formal & work dresses",
        "Casual dresses",
        "Strapless dresses",
        "Little black dresses",
        "Jean dresses",
        "Other dresses",
        "Mini skits",
        "Knee-length skirts",
        "Midi skirts",
        "Maxi skirts",
        "Asymmetric skirts",
        "Skorts",
        "Shirts",
        "Blouses",
        "Camis",
        "T-shirts",
        "Tank tops",
        "Tunics",
        "Crop tops",
        "Short-sleeved tops",
        "3/4-sleeve tops",
        "Long-sleeved tops",
        "Bodysuits",
        "Off-the-shoulder tops",
        "Turtlenecks",
        "Peplum tops",
        "Halter tops",
        "Other tops & t-shirts",
        "Boyfriend jeans",
        "Cropped jeans",
        "Flared jeans",
        "High-waisted jeans",
        "Ripped jeans",
        "Skinny jeans",
        "Straight jeans",
        "Cropped pants & chinos",
        "Wide—leg pants",
        "Skinny pants",
        "Tailored pants",
        "Straight-leg pants",
        "Leather pants",
        "Leggings",
        "Harem pants",
        "Other trousers",
        "Low-waist shorts",
        "High-waist shorts",
        "Knee-length shorts",
        "Jean shorts",
        "Lace shorts",
        "Leather shorts",
        "Cargo shorts",
        "Cropped pants",
        "Other shorts & cropped pants",
        "Jumpsuits",
        "Rompers",
        "Other jumpsuits & rompers",
        "One-pieces",
        "Bikinis & tankinis",
        "Cover-ups & sarongs",
        "Other swimwear & beachwear",
        "Bras",
        "Panties",
        "Sets",
        "Shapewear",
        "Sleepwear",
        "Dressing gowns",
        "Tights & stockings",
        "Socks",
        "Lingerie accessories",
        "Maternity clothes",
        "Tracksuits",
        "Outerwear",
        "Jerseys",
        "Hoodies & sweatshirts",
        "Glasses",
        "Gloves",
        "Hats",
        "Scarves",
        "Wristbands",
        "Sports bras",
        "Slim fit jeans",
        "Straight fit jeans",
        "Duffle coats",
        "Overcoats & long coats",
        "Parkas",
        "Peacoats",
        "Raincoats",
        "Trench coats",
        "Plain T-shirts",
        "Print T-shirts",
        "Stripped T-shirts",
        "Polo shirts",
        "Long-sleeved T-shirts",
        "Checked shirts",
        "Denim shirts",
        "Plain shirts",
        "Print shirts",
        "Stripped shirts",
        "Sweaters",
        "Zip-up hoodies & sweatshirts",
        "Cardigans",
        "Crew neck sweaters",
        "V-neck sweaters",
        "Turtleneck sweaters",
        "Long sweaters",
        "Thick-knit sweaters",
        "Sweater vests",
        "Wide-leg pants",
        "Cropped pants",
        "Tailored pants",
        "Cargo shorts",
        "Underwear",
        "Socks",
        "Bathrobes",
        "One-piece pajamas",
        "Pajama bottoms",
        "Pajama sets",
        "Pajama tops"
    ]

    for item in clothing_items:
        main(item)
